/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;


public class buscar extends javax.swing.JPanel {

    
    public buscar() {
        initComponents();
        InitStyles();
    }
    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        texto1.putClientProperty("FlatLaf.style", "font: bold 14 $light.font");
        texto1.setForeground(Color.black);
        texto2.putClientProperty("FlatLaf.style", "font: bold 14 $light.font");
        texto2.setForeground(Color.black);
        texto3.putClientProperty("FlatLaf.style", "font: bold 14 $light.font");
        texto3.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        btnBusqMat = new javax.swing.JButton();
        btnBusqProv = new javax.swing.JButton();
        btnMenuEntrada = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Búsquedas");

        texto1.setText("Búsqueda de Clientes");

        texto2.setText("Búsqueda de Material");

        texto3.setText("Búsqueda de Proveedores");

        btnBusqMat.setBackground(new java.awt.Color(255, 161, 27));
        btnBusqMat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBusqMat.setForeground(new java.awt.Color(255, 255, 255));
        btnBusqMat.setText("Materiales");
        btnBusqMat.setBorder(null);
        btnBusqMat.setBorderPainted(false);
        btnBusqMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusqMatMouseClicked(evt);
            }
        });

        btnBusqProv.setBackground(new java.awt.Color(255, 161, 27));
        btnBusqProv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBusqProv.setForeground(new java.awt.Color(255, 255, 255));
        btnBusqProv.setText("Proveedores");
        btnBusqProv.setBorder(null);
        btnBusqProv.setBorderPainted(false);
        btnBusqProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusqProvMouseClicked(evt);
            }
        });

        btnMenuEntrada.setBackground(new java.awt.Color(255, 161, 27));
        btnMenuEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEntrada.setText("Entradas");
        btnMenuEntrada.setBorder(null);
        btnMenuEntrada.setBorderPainted(false);
        btnMenuEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEntrada.setIconTextGap(10);
        btnMenuEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuEntradaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(172, 172, 172))
                    .addComponent(btnMenuEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addComponent(btnBusqMat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(texto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(115, 115, 115))
                    .addComponent(btnBusqProv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(btnMenuEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(btnBusqMat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(texto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(btnBusqProv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuEntradaMouseClicked
        buscarClienteF frame = new buscarClienteF();
        frame.setLocationRelativeTo(null); // centra la ventana
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMenuEntradaMouseClicked

    private void btnBusqMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusqMatMouseClicked
        buscarMaterialF frame = new buscarMaterialF();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnBusqMatMouseClicked

    private void btnBusqProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusqProvMouseClicked
        buscarProveedorF frame = new buscarProveedorF();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnBusqProvMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBusqMat;
    private javax.swing.JButton btnBusqProv;
    private javax.swing.JButton btnMenuEntrada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
