/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import BEAN.Usuario;

/**
 *
 * @author Julio
 */
public class dashboard extends javax.swing.JFrame {

    Usuario user;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        
        initComponents();
        InitStyles();
        SetDate();
        InitContent();
    }
    
    public void setUsuario(Usuario u) {
        user = u;
    }
    private void InitContent(){
       ShowJPanel(new Principal());
    }
    
    public void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0,0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    private void InitStyles(){
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setBackground(Color.black);
        subtitle1.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        subtitle1.setForeground(Color.white);
        dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        dateText.setForeground(Color.white);
        textm.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        textm.setForeground(Color.white);
    }
    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        textm = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenuEntrada = new javax.swing.JButton();
        btnMenuBusquedas = new javax.swing.JButton();
        btnMenuSalidas = new javax.swing.JButton();
        btnMenuRegistros = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        subtitle1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1020, 640));
        setPreferredSize(new java.awt.Dimension(1020, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1163, 855));

        menu.setBackground(new java.awt.Color(245, 126, 21));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        textm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textm.setText("MENÚ");

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        btnMenuEntrada.setBackground(new java.awt.Color(255, 161, 27));
        btnMenuEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar-plus.png"))); // NOI18N
        btnMenuEntrada.setText("Entradas");
        btnMenuEntrada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMenuEntrada.setBorderPainted(false);
        btnMenuEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuEntrada.setIconTextGap(10);
        btnMenuEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuEntradaMouseClicked(evt);
            }
        });

        btnMenuBusquedas.setBackground(new java.awt.Color(255, 161, 27));
        btnMenuBusquedas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuBusquedas.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuBusquedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book-open-page-variant.png"))); // NOI18N
        btnMenuBusquedas.setText("Búsquedas");
        btnMenuBusquedas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMenuBusquedas.setBorderPainted(false);
        btnMenuBusquedas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuBusquedas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBusquedas.setIconTextGap(10);
        btnMenuBusquedas.addActionListener(this::btnMenuBusquedasActionPerformed);

        btnMenuSalidas.setBackground(new java.awt.Color(255, 161, 27));
        btnMenuSalidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuSalidas.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar-multiple-check.png"))); // NOI18N
        btnMenuSalidas.setText("Salidas");
        btnMenuSalidas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMenuSalidas.setBorderPainted(false);
        btnMenuSalidas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuSalidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuSalidas.setIconTextGap(10);
        btnMenuSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuSalidasMouseClicked(evt);
            }
        });

        btnMenuRegistros.setBackground(new java.awt.Color(255, 161, 27));
        btnMenuRegistros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file-chart.png"))); // NOI18N
        btnMenuRegistros.setText("Registros");
        btnMenuRegistros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnMenuRegistros.setBorderPainted(false);
        btnMenuRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuRegistros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuRegistros.setIconTextGap(10);
        btnMenuRegistros.addActionListener(this::btnMenuRegistrosActionPerformed);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textm, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnMenuBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMenuRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMenuEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMenuSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(textm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnMenuBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnMenuRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMenuEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnMenuSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        header.setBackground(new java.awt.Color(255, 131, 22));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        subtitle1.setBackground(new java.awt.Color(255, 255, 255));
        subtitle1.setText("Administración/Control/Textilería");

        dateText.setBackground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {dayname}  {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(subtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setText("QALA TEXTIL");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(134, 134, 134))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(207, 207, 207))
        );

        jScrollPane1.setViewportView(background);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuEntradaMouseClicked
        registrarEntradaF frame = new registrarEntradaF();
        frame.setLocationRelativeTo(null); // centra la ventana
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setUsuario(user);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMenuEntradaMouseClicked

    private void btnMenuSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSalidasMouseClicked
        registrarSalidaF frame = new registrarSalidaF();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame.setUsuario(user);
        frame.setVisible(true);
    }//GEN-LAST:event_btnMenuSalidasMouseClicked

    private void btnMenuBusquedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBusquedasActionPerformed
        ShowJPanel(new buscar());
    }//GEN-LAST:event_btnMenuBusquedasActionPerformed

    private void btnMenuRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistrosActionPerformed
        registrar reg = new registrar();
        reg.setUsuario(user);
        ShowJPanel(reg);
    }//GEN-LAST:event_btnMenuRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // 1. INSTALAR EL DISEÑO PLANO (FLATLAF)
    try {
        // Opción A: Tema claro (el que parece que usas)
        com.formdev.flatlaf.FlatLightLaf.setup();
        
        // Opción B: Si prefieres el tema oscuro, usa este:
        // com.formdev.flatlaf.FlatDarkLaf.setup();
        
    } catch(Exception ex) {
        System.err.println("Falló al iniciar FlatLaf");
    }

    // 2. INICIAR LA VENTANA (Esto ya lo tenías, déjalo igual)
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new loginF().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnMenuBusquedas;
    private javax.swing.JButton btnMenuEntrada;
    private javax.swing.JButton btnMenuRegistros;
    private javax.swing.JButton btnMenuSalidas;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel subtitle1;
    private javax.swing.JLabel textm;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
